name: openra
summary: Libre/Free Real Time Strategy game engine supporting early Westwood classics
description: >
  Open Source real-time strategy game engine for early Westwood games
  such as Command & Conquer: Red Alert written in C# using SDL and
  OpenGL. Runs on Windows, Linux, *BSD and Mac OS X.
adopt-info: openra
grade: stable
confinement: strict
base: core20
compression: lzo

architectures:
- build-on: amd64
- build-on: armhf
- build-on: arm64

hooks:
  install:
    plugs:
      - network
  post-refresh:
    plugs:
      - network

apps:
  cnc:
    command: usr/local/bin/openra-cnc
    command-chain: [bin/desktop-launch]
    desktop: usr/local/share/applications/openra-cnc.desktop
    plugs:
    - audio-playback
    - avahi-control
    - avahi-observe
    - desktop
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11

  d2k:
    command: usr/local/bin/openra-d2k
    command-chain: [bin/desktop-launch]
    desktop: usr/local/share/applications/openra-d2k.desktop
    plugs:
    - audio-playback
    - avahi-control
    - avahi-observe
    - desktop
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11

  ra:
    command: usr/local/bin/openra-ra
    command-chain: [bin/desktop-launch]
    desktop: usr/local/share/applications/openra-ra.desktop
    plugs:
    - audio-playback
    - avahi-control
    - avahi-observe
    - desktop
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11

  # Not Available yet  
  # ts:
  #   command: usr/local/bin/openra-ts
  #   command-chain: [bin/desktop-launch]
  #   desktop: usr/local/share/applications/openra-ts.desktop
  #   plugs:
  #   - audio-playback
  #   - avahi-control
  #   - avahi-observe
  #   - desktop
  #   - mount-observe
  #   - network
  #   - network-bind
  #   - opengl
  #   - pulseaudio
  #   - removable-media
  #   - wayland
  #   - x11

parts:
  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  openra:
    after: [desktop-glib-only]
    plugin: make
    source: https://github.com/OpenRA/OpenRA.git
    override-pull: |
      snapcraftctl pull

      if [ -f "$SNAPCRAFT_PROJECT_DIR"/build-type ]; then
        . "$SNAPCRAFT_PROJECT_DIR"/build-type
      else
        PLAYTEST=false
      fi

      VERSION="$(curl -L -s https://api.github.com/repos/OpenRA/OpenRA/releases | jq -r '[.[] | select(.prerelease == '"$PLAYTEST"')] | .[0] | .tag_name')"
      # git checkout "$VERSION"
      # snapcraftctl set-version "$VERSION"
      snapcraftctl set-version main

      sed -i 's|^Icon=\(.*\)$|Icon=/usr/local/share/icons/hicolor/128x128/apps/\1.png|;s|^Exec=|Exec=openra.{MOD}|' packaging/linux/openra.desktop.in
      sed -i 's@\({BIN_DIR}\|{GAME_INSTALL_DIR}\)@$SNAP/\1@g' packaging/linux/openra.in
    override-build: |
      make version
      make RUNTIME=net5 all
      make RUNTIME=net5 DESTDIR=$SNAPCRAFT_PART_INSTALL install
      make RUNTIME=net5 DESTDIR=$SNAPCRAFT_PART_INSTALL install-linux-shortcuts
      make RUNTIME=net5 DESTDIR=$SNAPCRAFT_PART_INSTALL install-linux-appdata
    build-snaps: [dotnet-sdk/6.0/stable]
    build-packages:
    - curl
    - jq
    - libfreetype6-dev
    - libglu1-mesa-dev
    - liblua5.1-0-dev
    - libopenal-dev
    - libsdl2-dev
    - unzip
    stage-packages:
    - libfreetype6
    - libgdiplus
    - libglu1-mesa
    - liblttng-ust0
    - liblua5.1-0
    - libopenal1
    - libsdl2-2.0-0
    - mount
    - wget
