name: openra
summary: Libre/Free Real Time Strategy game engine supporting early Westwood classics
description: >
  Open Source real-time strategy game engine for early Westwood games
  such as Command & Conquer: Red Alert written in C# using SDL and
  OpenGL. Runs on Windows, Linux, *BSD and Mac OS X.
adopt-info: openra
grade: stable
confinement: strict
base: core18
compression: lzo

architectures:
- build-on: amd64
- build-on: i386
- build-on: armhf
  run-on: [armhf, arm64]
- build-on: ppc64el

layout:
  /usr/share/.mono:
    bind: $SNAP_COMMON/.mono

hooks:
  install:
    plugs:
      - network
  post-refresh:
    plugs:
      - network

environment:
  MONO_CFG_DIR: $SNAP/etc
  MONO_CONFIG: $SNAP/etc/mono/config
  MONO_GAC_PREFIX: $SNAP/usr/lib/mono

apps:
  cnc:
    command: usr/local/bin/openra-cnc
    command-chain: [bin/desktop-launch]
    desktop: usr/local/share/applications/openra-cnc.desktop
    plugs:
    - audio-playback
    - avahi-control
    - avahi-observe
    - desktop
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11

  d2k:
    command: usr/local/bin/openra-d2k
    command-chain: [bin/desktop-launch]
    desktop: usr/local/share/applications/openra-d2k.desktop
    plugs:
    - audio-playback
    - avahi-control
    - avahi-observe
    - desktop
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11

  ra:
    command: usr/local/bin/openra-ra
    command-chain: [bin/desktop-launch]
    desktop: usr/local/share/applications/openra-ra.desktop
    plugs:
    - audio-playback
    - avahi-control
    - avahi-observe
    - desktop
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11

  # Not Available yet  
  # ts:
  #   command: usr/local/bin/openra-ts
  #   command-chain: [bin/desktop-launch]
  #   desktop: usr/local/share/applications/openra-ts.desktop
  #   plugs:
  #   - audio-playback
  #   - avahi-control
  #   - avahi-observe
  #   - desktop
  #   - mount-observe
  #   - network
  #   - network-bind
  #   - opengl
  #   - pulseaudio
  #   - removable-media
  #   - wayland
  #   - x11

package-repositories:
  - type: apt
    formats: [deb]
    components: [main]
    suites: [stable-bionic]
    key-id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    url: https://download.mono-project.com/repo/ubuntu

parts:
  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  openra:
    after: [desktop-glib-only]
    plugin: make
    source: https://github.com/OpenRA/OpenRA.git
    build-environment:
    - MONO_CFG_DIR: $SNAPCRAFT_PART_INSTALL/etc
    - MONO_CONFIG: $SNAPCRAFT_PART_INSTALL/etc/mono/config
    - MONO_GAC_PREFIX: $SNAPCRAFT_PART_INSTALL/usr/lib/mono
    override-pull: |
      snapcraftctl pull

      if [ -f "$SNAPCRAFT_PROJECT_DIR"/build-type ]; then
        . "$SNAPCRAFT_PROJECT_DIR"/build-type
      else
        PLAYTEST=false
      fi

      VERSION="$(curl -L -s https://api.github.com/repos/OpenRA/OpenRA/releases | jq '[.[] | select(.prerelease == '"$PLAYTEST"')] | .[0] | .tag_name' | sed -e 's/"//g')"
      git checkout "$VERSION"
      snapcraftctl set-version "$VERSION"

      sed -i 's|^Icon=\(.*\)$|Icon=/usr/local/share/icons/hicolor/128x128/apps/\1.png|;s|^Exec=|Exec=openra.{MOD}|' packaging/linux/openra.desktop.in
      sed -i 's@\({BIN_DIR}\|{GAME_INSTALL_DIR}\)@$SNAP/\1@g' packaging/linux/openra.in
    override-build: |
      make version
      make all
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install-linux-shortcuts
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install-linux-appdata
    build-packages:
    - curl
    - jq
    - libfreetype6-dev
    - libglu1-mesa-dev
    - liblua5.1-0-dev
    - libopenal-dev
    - libsdl2-dev
    - mono-complete
    - nuget
    - unzip
    stage-packages:
    - ca-certificates-mono
    - libfreetype6
    - libgdiplus
    - libglu1-mesa
    - liblua5.1-0
    - libopenal1
    - libsdl2-2.0-0
    - mono-devel
    - mount
    - wget
